# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prohelp.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("prohelp.proto", :syntax => :proto3) do
    add_message "prohelp.ProtoRequest" do
      optional :request, :string, 1
    end
    add_message "prohelp.ProtoResponse" do
      optional :response, :string, 1
    end
  end
end

module Prohelp
  ProtoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("prohelp.ProtoRequest").msgclass
  ProtoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("prohelp.ProtoResponse").msgclass
end
